# Please refer to https://stash.us.cray.com/projects/CLOUD/repos/cray-charts/browse/stable/cray-service/values.yaml?at=refs%2Fheads%2Fmaster
# for more info on values you can set/override
# Note that cray-service.containers[*].image and cray-service.initContainers[*].image map values are one of the only structures that
# differ from the standard kubernetes container spec:
# image:
#   repository: ""
#   tag: "" (default = "latest")
#   pullPolicy: "" (default = "IfNotPresent")

global:
  appVersion: 1.15.0

image:
  repository: artifactory.algol60.net/csm-docker/stable/cray-hbtd
  pullPolicy: IfNotPresent

cray-service:
  type: "Deployment"
  nameOverride: "cray-hbtd"
  fullnameOverride: "cray-hbtd"
  replicaCount: 3
  etcdCluster:
    enabled: true
    pvc:
      storage: 8Gi
    compactionMode: revision
    compactionRetention: "100000"
    snapshotMax: "1"
    snapshotCount: "5000000"
    heartbeatInterval: "4200"
    enforceAntiAffinity: "21000"
    resources:
      limits:
        cpu: 4
        memory: 8Gi
      requests:
        cpu: 10m
        memory: 64Mi
  containers:
    cray-hbtd:
      name: "cray-hbtd"
      image:
        repository: "artifactory.algol60.net/csm-docker/stable/cray-hbtd"
      ports:
        - name: http
          containerPort: 28500
      env:
        - name: SM_URL
          value: "http://cray-smd/hsm/v1"
        - name: WARNTIME
          value: "35"
        - name: ERRTIME
          value: "60"
      livenessProbe:
        httpGet:
          port: 28500
          path: /hmi/v1/liveness
        initialDelaySeconds: 10
        periodSeconds: 30
      readinessProbe:
        httpGet:
          port: 28500
          path: /hmi/v1/readiness
        initialDelaySeconds: 15
        periodSeconds: 30
      resources:
        limits:
          cpu: "4"
          memory: 2Gi
        requests:
          cpu: 64m
          memory: 512Mi
  podAnnotations:
    traffic.sidecar.istio.io/excludeOutboundPorts: 8082,9092,2181,2379,2380
  ingress:
    enabled: true
    uri: " "
    prefix: "/apis/hbtd"
